version: "3.9"
services:

  postgres: 
    image: postgres:15-alpine 
    container_name: VOD_postgres
    restart: always
    environment: 
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: vod_db   
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:

    

    
