import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'language',
})
export class LanguagePipe implements PipeTransform {
  private languageMap: { [key: string]: string } = {
    en: 'English',
    fr: 'French',
    es: 'Spanish',
    de: 'German',
    ar: 'Arabic',
    it: 'Italian',
    zh: 'Chinese (Simplified)',
    'zh-TW': 'Chinese (Traditional)',
    ja: 'Japanese',
    ru: 'Russian',
    hi: 'Hindi',
    pt: 'Portuguese',
    bn: 'Bengali',
    ko: 'Korean',
    tr: 'Turkish',
    vi: 'Vietnamese',
    nl: 'Dutch',
    sv: 'Swedish',
    pl: 'Polish',
    id: 'Indonesian',
    uk: 'Ukrainian',
    fa: 'Persian',
    th: 'Thai',
    he: 'Hebrew',
    el: 'Greek',
    cs: 'Czech',
    ro: 'Romanian',
    hu: 'Hungarian',
    da: 'Danish',
    fi: 'Finnish',
    no: 'Norwegian',
    sk: 'Slovak',
    bg: 'Bulgarian',
    sr: 'Serbian',
    hr: 'Croatian',
    lt: 'Lithuanian',
    sl: 'Slovenian',
    et: 'Estonian',
    lv: 'Latvian',
    ms: 'Malay',
    tl: 'Tagalog',
    sw: 'Swahili',
    am: 'Amharic',
    ur: 'Urdu',
    pa: 'Punjabi',
    my: 'Burmese',
    km: 'Khmer',
    lo: 'Lao',
    ml: 'Malayalam',
    ta: 'Tamil',
    te: 'Telugu',
    kn: 'Kannada',
    mr: 'Marathi',
    gu: 'Gujarati',
    si: 'Sinhala',
    az: 'Azerbaijani',
    ka: 'Georgian',
    hy: 'Armenian',
    mn: 'Mongolian',
    kk: 'Kazakh',
    uz: 'Uzbek',
    tg: 'Tajik',
    tk: 'Turkmen',
    ps: 'Pashto',
    sd: 'Sindhi',
    xh: 'Xhosa',
    zu: 'Zulu',
    ig: 'Igbo',
    yo: 'Yoruba',
    ha: 'Hausa',
    rw: 'Kinyarwanda',
    so: 'Somali',
  };

  transform(value: string): string {
    return this.languageMap[value] || value;
  }
}
