# Generated by Django 6.0.7 on 2026-07-27 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('role', models.CharField(choices=[('actor', 'Diễn viên'), ('director', 'Đạo diễn'), ('both', 'Cả hai')], default='actor', max_length=20)),
                ('avatar', models.URLField(blank=True, help_text='Ảnh chân dung')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên gói (VD: VIP Hàng Tháng)', max_length=100)),
                ('code', models.SlugField(help_text='Mã gói (VD: vip_monthly)', unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá gói (VNĐ)', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(help_text='Số ngày sử dụng')),
                ('max_resolution', models.CharField(default='1080p', help_text='Chất lượng (720p, 1080p, 4K)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='episode',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Cho xem thử miễn phí (VD: Tập 1 free)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Hiển thị ở Slider/Đề xuất trang chủ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_vip_only',
            field=models.BooleanField(default=False, help_text='Yêu cầu tài khoản VIP mới được xem'),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, help_text='Tên gốc tiếng Anh/Hàn...', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Tổng thời lượng video (giây)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.URLField(help_text='Link phát video HLS/MP4'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Thời lượng tính theo phút (dành cho Phim lẻ)', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá mua/thuê lẻ (VNĐ)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link video phát trực tiếp (chỉ dùng cho Phim lẻ)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies_app.category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(blank=True, help_text='Diễn viên & Đạo diễn', related_name='movies', to='movies_app.person'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, help_text='Tên mùa (Ví dụ: Mùa 1)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies_app.movie')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('movie', 'season_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies_app.season'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('movie', 'season', 'episode_number')},
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies_app.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
